import request from '@/utils/request'

export const login = (data) => request.post('/auth/login', data)
export const register = (data) => request.post('/auth/register', data)
export const getUserInfo = () => request.get('/user/info')
export const updateUserInfo = (data) => request.put('/user/info', data)
export const changePassword = (data) => request.put('/user/password', data)
export const getMyTasks = () => request.get('/tasks/my')
export const getTeamTasks = (teamId) => request.get(`/tasks/team/${teamId}`)
export const getTeamMemberStats = (teamId) => request.get(`/tasks/team/${teamId}/stats`)
export const createTask = (data) => request.post('/tasks', data)
export const updateTask = (id, data) => request.put(`/tasks/${id}`, data)
export const deleteTask = (id) => request.delete(`/tasks/${id}`)
export const getMyTeams = () => request.get('/teams/my')
export const createTeam = (data) => request.post('/teams', data)
export const joinTeam = (teamId) => request.post(`/teams/${teamId}/join`)
export const deleteTeam = (teamId) => request.delete(`/teams/${teamId}`)
export const inviteMember = (teamId, data) => request.post(`/teams/${teamId}/invite`, data)
export const getTeamMembers = (teamId) => request.get(`/teams/${teamId}/members`)
export const removeMember = (teamId, memberId) => request.delete(`/teams/${teamId}/members/${memberId}`)
